package com.lowyinstitute.asiapowerindex.enums;

public enum MeasureName {
    ECONOMIC_CAPABILITY,
    MILITARY_CAPABILITY,
    RESILIENCE,
    FUTURE_RESOURCES,
    ECONOMIC_RELATIONSHIPS,
    DEFENCE_NETWORKS,
    DIPLOMATIC_INFLUENCE,
    CULTURAL_INFLUENCE,
    COMPREHENSIVE_POWER
}
